spring:
  application:
    name: adg-rule
  profiles:
    active: prod  # Switch to dev to output debug information

logging:
  file:
    path: ./logs

application:
  rule:
    # Remote rules
    remote:
      # - 'https://cdn.jsdelivr.net/gh/hoshsadiq/adblock-nocoin-list/hosts.txt'  # adblock-nocoin-list
      - 'https://raw.githubusercontent.com/durablenapkin/scamblocklist/refs/heads/master/adguard.txt' # Scam Blocklist
      - 'https://someonewhocares.org/hosts/zero/hosts' # Dan Pollock's List
      - 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext' # Peter Lowe's List
      # - 'https://abp.oisd.nl/basic/' # OISD Blocklist Basic
      - 'https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/refs/heads/master/data/hosts/spy.txt' # WindowsSpyBlocker
      - 'https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts' # DaSheng Ad Clean
      - 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt' # adguard base
      - 'https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_trackers.txt' # name: AdGuard CNAME disguised tracker list
      - 'https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt' # name: AdGuard DNS filter
      - 'https://raw.githubusercontent.com/Crystal-RainSlide/AdditionalFiltersCN/master/CN.txt' # name: AdditionalFiltersCN
      - 'https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt' # name: ADgk mobile ad rules
      - 'https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt' # name: ChengFeng ad filter rules
      - 'https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt' # name: ChengFeng video filter rules
      - 'https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad.txt' # name: HalfLife_merged from ChengFeng video ad filter rules, EasylistChina, EasylistLite, CJX'sAnnoyance
      - 'https://adaway.org/hosts.txt' # name: AdAway official ad-blocking Host rules
      - 'https://easylist-downloads.adblockplus.org/antiadblockfilters.txt' # name: Remove anti-adblock warning rules
      - 'https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt' # name: XingShao AdRules DNS List
      # - 'https://raw.githubusercontent.com/xiebaiyuan/adrule/refs/heads/adrules/dns.txt' # name: catteam
      # 这个作者好像有点恨百度 热榜都干了。
      # - 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/AdGuard/Advertising/Advertising.txt' # name: AdGuard_blackmatrix7 merged
      - 'https://raw.githubusercontent.com/zsakvo/AdGuard-Custom-Rule/master/rule/zhihu.txt' # name: Zhihu standard version
      - 'https://raw.githubusercontent.com/timlu85/AdGuard-Home_Youtube-Adfilter/master/Youtube-Adfilter-Web.txt' # name: Youtube-Adfilter-Web
      - 'https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt' # name: Autumn Wind ad rules, targeting Android ads
      # KoolProxy rules
      # - 'https://raw.githubusercontent.com/ilxp/koolproxy/main/rules/koolproxy.txt' # name: static whitelist rules
      # - 'https://github.com/ilxp/koolproxy/raw/main/rules/daily.txt' # name: daily rules
      # - 'https://github.com/ilxp/koolproxy/raw/main/rules/steven.txt' # name: StevenBlack rules
      - 'https://raw.githubusercontent.com/ilxp/koolproxy/refs/heads/main/rules/adg.txt' # name: koolproxy adg rules
      - 'https://raw.githubusercontent.com/ilxp/koolproxy/refs/heads/main/rules/antiad.txt' # name: koolproxy antiad rules
      # uBlock built-in rules
      - 'https://raw.githubusercontent.com/uBlockOrigin/uAssets/refs/heads/master/filters/filters.txt' # name: uBlock filters
      - 'https://ublockorigin.pages.dev/filters/badware.txt' # name: uBlock filters – Badware risks
      - 'https://raw.githubusercontent.com/uBlockOrigin/uAssetsCDN/refs/heads/main/filters/privacy.min.txt' # name: uBlock filters – Privacy
      - 'https://ublockorigin.github.io/uAssets/filters/quick-fixes.txt' # name: uBlock filters – Quick fixes
      - 'https://raw.githubusercontent.com/uBlockOrigin/uAssets/refs/heads/master/filters/resource-abuse.txt' # name: uBlock filters – Resource abuse
      - 'https://raw.githubusercontent.com/uBlockOrigin/uAssetsCDN/refs/heads/main/filters/unbreak.txt' # name: uBlock filters – Unbreak
      - 'https://filters.adtidy.org/extension/ublock/filters/11.txt' # name: AdGuard Mobile Ads mobile devices
      # PCDN rules
      - 'https://raw.githubusercontent.com/thhbdd/Block-pcdn-domains/refs/heads/main/ban.txt' # name: fuck pcdn
      # Anti AD 
      - 'https://anti-ad.net/easylist.txt' # name: anti-AD
      # Anti AD PCDN
      - 'https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/refs/heads/master/discretion/pcdn.txt' # name: anti-AD PCDN rules
      # Anti AD http dns
      - 'https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/refs/heads/master/discretion/dns.txt' # name: anti-AD httpdns
    # Local rules
    local: # Local rules please move files to the rule directory in the project path
      - 'mylist.txt'
  output:
    path: rule   # Rule file output path, relative path defaults from project directory
    files:
      all.txt:    # Output filename
        - DOMAIN  # Domain rules, complete domain names only
        - REGEX   # Regex rules, domain rules containing regex, AdGH supports
        - MODIFY  # Modifier rules, rules with added modifier symbols, AdG supports
        - HOSTS   # Hosts rules
      adgh.txt:
        - DOMAIN
        - REGEX
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
